### ISSUE TITLE
Please update to MIUI 7

### ISSUE THREAD

**Issue by What-Zit-Tooya** [CodeingBoy/DisableMIUIRootCountDown#1]
Hello, please update to MIUI 7.

**Comment by CodeingBoy** [comment]
Sorry, I no longer use MIUI.So I can't update it to MIUI 7.
Besides, there is no compatible Xposed framework for MIUI 7 based on Android 5.0+.

**Comment by CodeingBoy** [comment]
Eh...I just update my MI 2 to MIUI 7. With Xposed for MIUI 7 on Android 5.0, this module works well.
So I will not modify this module.
And this project will be discontinued.

**Comment by What-Zit-Tooya** [comment]
How about mithemes for MIUI 7?

**Comment by CodeingBoy** [comment]
I don't know.I didn't test mithemes.

**Comment by What-Zit-Tooya** [comment]
mithemes is abandoned module, it won't work on miui 7, but if you modify source code for mithemes, im sure it will work.
I want to modify it, but i don't know how to, i dont know about java programe + create xposed app.

**Comment by CodeingBoy** [comment]
First, I don't use MIUI at all. (all my devices including XiaoMi devices had flashed stock Android or CyanogenMod)
Second, I don't like cracking.
Third, now I have no time to program other stuff.(I have to learn C, C++, Java and more...)
So. Sorry. I really don't want to take this.
